/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import com.formdev.flatlaf.FlatLightLaf;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author alessandro
 */
public class form_login extends javax.swing.JFrame {

    /**
     * Creates new form form_masuk
     */
    private static Point point = new Point();

    public form_login() {
        setSize(768, 640);
        setResizable(false);
        setLocationRelativeTo(null);

        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar dari program?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    setDefaultCloseOperation(form_login.DISPOSE_ON_CLOSE);
                } else if (confirm == JOptionPane.NO_OPTION) {
                    setDefaultCloseOperation(form_login.DO_NOTHING_ON_CLOSE);
                }
            }
        });

        initComponents();

        ImageIcon logo = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        Image logo1 = logo.getImage();
        Image logo2 = logo1.getScaledInstance(logo_set.getWidth(), logo_set.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(logo2);
        logo_set.setIcon(i);

        icon_hide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_masuk = new javax.swing.JPanel();
        panel_half_masuk = new javax.swing.JPanel();
        logo_set = new javax.swing.JLabel();
        label_kecamatan = new javax.swing.JLabel();
        label_ratahan = new javax.swing.JLabel();
        label_selamatdatang = new javax.swing.JLabel();
        fld_username = new placeholder.username();
        fld_password = new placeholder.password();
        btn_masuk = new javax.swing.JPanel();
        label_btn_masuk = new javax.swing.JLabel();
        icon_show = new javax.swing.JLabel();
        icon_hide = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bg_masuk.setBackground(new java.awt.Color(247, 247, 247));

        panel_half_masuk.setBackground(new java.awt.Color(72, 60, 50));

        label_kecamatan.setFont(new java.awt.Font("Lora", 1, 36)); // NOI18N
        label_kecamatan.setForeground(new java.awt.Color(255, 255, 255));
        label_kecamatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_kecamatan.setText("KECAMATAN");

        label_ratahan.setFont(new java.awt.Font("Lora", 1, 36)); // NOI18N
        label_ratahan.setForeground(new java.awt.Color(255, 255, 255));
        label_ratahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ratahan.setText("RATAHAN");

        javax.swing.GroupLayout panel_half_masukLayout = new javax.swing.GroupLayout(panel_half_masuk);
        panel_half_masuk.setLayout(panel_half_masukLayout);
        panel_half_masukLayout.setHorizontalGroup(
            panel_half_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_half_masukLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(logo_set, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(panel_half_masukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_half_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_ratahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_half_masukLayout.setVerticalGroup(
            panel_half_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_half_masukLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(logo_set, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label_ratahan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        label_selamatdatang.setFont(new java.awt.Font("Karla", 1, 24)); // NOI18N
        label_selamatdatang.setForeground(new java.awt.Color(72, 60, 50));
        label_selamatdatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_selamatdatang.setText("Selamat Datang!");

        fld_username.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        fld_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_usernameKeyReleased(evt);
            }
        });

        fld_password.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        fld_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_passwordKeyReleased(evt);
            }
        });

        btn_masuk.setBackground(new java.awt.Color(72, 60, 50));
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });

        label_btn_masuk.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_btn_masuk.setForeground(new java.awt.Color(255, 255, 255));
        label_btn_masuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_btn_masuk.setText("Masuk");

        javax.swing.GroupLayout btn_masukLayout = new javax.swing.GroupLayout(btn_masuk);
        btn_masuk.setLayout(btn_masukLayout);
        btn_masukLayout.setHorizontalGroup(
            btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_masukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_btn_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_masukLayout.setVerticalGroup(
            btn_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        icon_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_eye_32px.png"))); // NOI18N
        icon_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_showMouseClicked(evt);
            }
        });

        icon_hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_invisible_32px.png"))); // NOI18N
        icon_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_hideMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_bg_masukLayout = new javax.swing.GroupLayout(panel_bg_masuk);
        panel_bg_masuk.setLayout(panel_bg_masukLayout);
        panel_bg_masukLayout.setHorizontalGroup(
            panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_masukLayout.createSequentialGroup()
                .addComponent(panel_half_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bg_masukLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fld_username)
                            .addComponent(label_selamatdatang, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addGroup(panel_bg_masukLayout.createSequentialGroup()
                                .addComponent(fld_password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(icon_show)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(icon_hide)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bg_masukLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        panel_bg_masukLayout.setVerticalGroup(
            panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_masukLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(label_selamatdatang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fld_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fld_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bg_masukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon_hide)
                        .addComponent(icon_show)))
                .addGap(18, 18, 18)
                .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel_half_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_hideMouseClicked
        // TODO add your handling code here:
        icon_hide.setVisible(false);
        icon_show.setVisible(true);
        fld_password.setEchoChar('*');
    }//GEN-LAST:event_icon_hideMouseClicked

    private void icon_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_showMouseClicked
        // TODO add your handling code here:
        icon_show.setVisible(false);
        icon_hide.setVisible(true);
        fld_password.setEchoChar((char) 0);
    }//GEN-LAST:event_icon_showMouseClicked

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btn_masukMouseClicked

    private void fld_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_passwordKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_fld_passwordKeyReleased

    private void fld_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_usernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_fld_usernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", true);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    private void login() {
        if (fld_username.getText().equals("") || fld_password.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ID Pengguna dan Kata Sandi tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql = "SELECT * FROM login WHERE username = '" + fld_username.getText() + "' AND password = '" + fld_password.getText() + "'";
                Connection con = new database.connection().configDB();
                java.sql.Statement stat = con.createStatement();
                java.sql.ResultSet hasil = stat.executeQuery(sql);

                if (hasil.next()) {
                    try {
                        String username = hasil.getString("username");
                        String password = hasil.getString("password");
                        String access = hasil.getString("access");

                        if (fld_username.getText().equals(username) && fld_password.getText().equals(password) && access.equals("admin")) {
                            form_superadmin superadmin = new form_superadmin();
                            superadmin.setVisible(true);
                            this.setVisible(false);

                            JOptionPane.showMessageDialog(null, "Selamat Datang!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                        } else if (fld_username.getText().equals(username) && fld_password.getText().equals(password) && access.equals("kasubbag")) {
                            form_admin admin = new form_admin();
                            admin.setVisible(true);
                            this.setVisible(false);

                            JOptionPane.showMessageDialog(null, "Selamat Datang!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        } else if (fld_username.getText().equals(username) && fld_password.getText().equals(password) && access.equals("user")) {
                            form_user user = new form_user(username);
                            user.setVisible(true);
                            this.setVisible(false);

                            JOptionPane.showMessageDialog(null, "Selamat Datang!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Gagal menampilkan Halaman Beranda!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        hasil.close();
                        stat.close();
                        con.close();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nama Pengguna atau Kata Sandi yang anda masukkan salah!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Query Error!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_masuk;
    private javax.swing.JPasswordField fld_password;
    private javax.swing.JTextField fld_username;
    private javax.swing.JLabel icon_hide;
    private javax.swing.JLabel icon_show;
    private javax.swing.JLabel label_btn_masuk;
    private javax.swing.JLabel label_kecamatan;
    private javax.swing.JLabel label_ratahan;
    private javax.swing.JLabel label_selamatdatang;
    private javax.swing.JLabel logo_set;
    private javax.swing.JPanel panel_bg_masuk;
    private javax.swing.JPanel panel_half_masuk;
    // End of variables declaration//GEN-END:variables
}
