/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author alessandro
 */
public class form_detail_datapegawai extends javax.swing.JDialog {

    /**
     * Creates new form form_detail_datapegawai
     */
    private static Point point = new Point();

    public form_detail_datapegawai(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);

        setSize(1024, 660);
        setResizable(false);
        setLocationRelativeTo(null);

        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        initComponents();

        tampil_datapegawai(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_detail_datapegawai = new javax.swing.JPanel();
        label_detail_datapegawai = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        set_jeniskelamin = new javax.swing.JLabel();
        set_eselon = new javax.swing.JLabel();
        set_pangkat = new javax.swing.JLabel();
        set_jabatan = new javax.swing.JLabel();
        label_jeniskelamion = new javax.swing.JLabel();
        set_ttl = new javax.swing.JLabel();
        set_alamat = new javax.swing.JLabel();
        set_statuskawin = new javax.swing.JLabel();
        set_nama = new javax.swing.JLabel();
        label_jabatan_profil = new javax.swing.JLabel();
        label_eselon_profil = new javax.swing.JLabel();
        label_umur = new javax.swing.JLabel();
        label_statuskawin = new javax.swing.JLabel();
        set_umur = new javax.swing.JLabel();
        label_pangkat_profil = new javax.swing.JLabel();
        label_agama = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        profilepic = new javax.swing.JLabel();
        set_agama = new javax.swing.JLabel();
        set_nip = new javax.swing.JLabel();
        label_ttl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bg_detail_datapegawai.setBackground(new java.awt.Color(247, 247, 247));

        label_detail_datapegawai.setFont(new java.awt.Font("Karla", 1, 36)); // NOI18N
        label_detail_datapegawai.setForeground(new java.awt.Color(72, 60, 50));
        label_detail_datapegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_detail_datapegawai.setText("DETAIL DATA PEGAWAI");

        set_jeniskelamin.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_jeniskelamin.setText("Jenis Kelamin Set");

        set_eselon.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_eselon.setText("Eselon Set");

        set_pangkat.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_pangkat.setText("Pangkat Set");

        set_jabatan.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_jabatan.setText("Jabatan Set");

        label_jeniskelamion.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_jeniskelamion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_jeniskelamion.setText("Jenis Kelamin");

        set_ttl.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_ttl.setText("Tempat Tanggal Lahir Set");

        set_alamat.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_alamat.setText("Alamat Set");

        set_statuskawin.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_statuskawin.setText("Status Kawin Set");

        set_nama.setFont(new java.awt.Font("Karla", 1, 24)); // NOI18N
        set_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set_nama.setText("Nama");

        label_jabatan_profil.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_jabatan_profil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_jabatan_profil.setText("Jabatan");

        label_eselon_profil.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_eselon_profil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_eselon_profil.setText("Eselon");

        label_umur.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_umur.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_umur.setText("Umur");

        label_statuskawin.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_statuskawin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_statuskawin.setText("Status Kawin");

        set_umur.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_umur.setText("Umur Set");

        label_pangkat_profil.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_pangkat_profil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_pangkat_profil.setText("Pangkat");

        label_agama.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_agama.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_agama.setText("Agama");

        label_alamat.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_alamat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_alamat.setText("Alamat");

        profilepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halaman/default.png"))); // NOI18N

        set_agama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        set_agama.setText("Agama Set");

        set_nip.setFont(new java.awt.Font("Karla", 0, 24)); // NOI18N
        set_nip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set_nip.setText("NIP");

        label_ttl.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_ttl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_ttl.setText("Tempat Tanggal Lahir");

        javax.swing.GroupLayout panel_bg_detail_datapegawaiLayout = new javax.swing.GroupLayout(panel_bg_detail_datapegawai);
        panel_bg_detail_datapegawai.setLayout(panel_bg_detail_datapegawaiLayout);
        panel_bg_detail_datapegawaiLayout.setHorizontalGroup(
            panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_detail_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(set_nip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilepic, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_ttl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_jeniskelamion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_umur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_agama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_statuskawin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(set_jeniskelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_ttl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_umur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_agama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_statuskawin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_pangkat_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_jabatan_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_eselon_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(set_pangkat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(set_eselon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        panel_bg_detail_datapegawaiLayout.setVerticalGroup(
            panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_detail_datapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(label_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_umur, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_statuskawin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(set_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_jeniskelamion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(set_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_umur, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_statuskawin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addComponent(profilepic)
                        .addGap(18, 18, 18)
                        .addComponent(set_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(set_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_bg_detail_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_pangkat_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_jabatan_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_eselon_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_detail_datapegawaiLayout.createSequentialGroup()
                                .addComponent(set_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(set_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(set_eselon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_detail_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_detail_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", true);

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_detail_datapegawai dialog = new form_detail_datapegawai(new javax.swing.JFrame(), true, "0");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void tampil_datapegawai(String id) {
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT *,\n"
                    + "TIMESTAMPDIFF(YEAR, tanggal_lahir, CURDATE()) AS umur,\n"
                    + "CONCAT(tempat_lahir, ', ', DATE_FORMAT(tanggal_lahir, '%e %b %Y')) AS ttl\n"
                    + "FROM datapegawai\n"
                    + "JOIN pangkat ON datapegawai.id_pangkat = pangkat.id_pangkat\n"
                    + "JOIN jabatan ON datapegawai.id_jabatan = jabatan.id_jabatan\n"
                    + "JOIN eselon ON datapegawai.id_eselon = eselon.id_eselon\n"
                    + "WHERE id_pegawai = '" + id + "'";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            if (hasil.next()) {
                try {
                    set_nama.setText(hasil.getString("nama"));
                    set_nip.setText(hasil.getString("nip"));
                    set_jeniskelamin.setText(hasil.getString("jenis_kelamin"));
                    set_ttl.setText(hasil.getString("ttl"));
                    set_umur.setText(hasil.getString("umur"));
                    set_agama.setText(hasil.getString("agama"));
                    set_statuskawin.setText(hasil.getString("status_kawin"));
                    set_alamat.setText(hasil.getString("alamat"));
                    set_pangkat.setText(hasil.getString("nama_pangkat"));
                    set_jabatan.setText(hasil.getString("nama_jabatan"));
                    set_eselon.setText(hasil.getString("nama_eselon"));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menampilkan Data Pegawai!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } finally {
                    hasil.close();
                    stat.close();
                    con.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ada!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Query Error!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_agama;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_detail_datapegawai;
    private javax.swing.JLabel label_eselon_profil;
    private javax.swing.JLabel label_jabatan_profil;
    private javax.swing.JLabel label_jeniskelamion;
    private javax.swing.JLabel label_pangkat_profil;
    private javax.swing.JLabel label_statuskawin;
    private javax.swing.JLabel label_ttl;
    private javax.swing.JLabel label_umur;
    private javax.swing.JPanel panel_bg_detail_datapegawai;
    private javax.swing.JLabel profilepic;
    private javax.swing.JLabel set_agama;
    private javax.swing.JLabel set_alamat;
    private javax.swing.JLabel set_eselon;
    private javax.swing.JLabel set_jabatan;
    private javax.swing.JLabel set_jeniskelamin;
    private javax.swing.JLabel set_nama;
    private javax.swing.JLabel set_nip;
    private javax.swing.JLabel set_pangkat;
    private javax.swing.JLabel set_statuskawin;
    private javax.swing.JLabel set_ttl;
    private javax.swing.JLabel set_umur;
    // End of variables declaration//GEN-END:variables
}
