/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alessandro
 */
public class form_sandi_user extends javax.swing.JDialog {

    /**
     * Creates new form form_akun
     */
    DefaultTableModel tabel1 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private static Point point = new Point();

    public form_sandi_user(java.awt.Frame parent, boolean modal, String id, String username) {
        super(parent, modal);

        setSize(800, 600);
        setResizable(false);
        setLocationRelativeTo(null);

        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        initComponents();

        id_container.setText(id);
        id_container.setVisible(false);
        fld_idpengguna.setText(username);
        label_tidakcocok.setVisible(false);
    }

    private form_sandi_user(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_akun = new javax.swing.JPanel();
        label_akun = new javax.swing.JLabel();
        label_idpengguna = new javax.swing.JLabel();
        label_sandilama = new javax.swing.JLabel();
        label_sandibaru = new javax.swing.JLabel();
        fld_idpengguna = new javax.swing.JTextField();
        fld_sandilama = new javax.swing.JTextField();
        fld_sandibaru = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JPanel();
        label_btn_simpan = new javax.swing.JLabel();
        id_container = new javax.swing.JLabel();
        fld_konfsandilama = new javax.swing.JTextField();
        label_sandilama1 = new javax.swing.JLabel();
        label_tidakcocok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bg_akun.setBackground(new java.awt.Color(247, 247, 247));

        label_akun.setFont(new java.awt.Font("Karla", 1, 36)); // NOI18N
        label_akun.setForeground(new java.awt.Color(72, 60, 50));
        label_akun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_akun.setText("GANTI SANDI");

        label_idpengguna.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_idpengguna.setText("ID Pengguna");

        label_sandilama.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_sandilama.setText("Sandi Lama");

        label_sandibaru.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_sandibaru.setText("Sandi Baru");

        fld_idpengguna.setEditable(false);
        fld_idpengguna.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        fld_sandilama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        fld_sandibaru.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        btn_simpan.setBackground(new java.awt.Color(72, 60, 50));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });

        label_btn_simpan.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        label_btn_simpan.setForeground(new java.awt.Color(255, 255, 240));
        label_btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_32px.png"))); // NOI18N
        label_btn_simpan.setText("SIMPAN");
        label_btn_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIconTextGap(2);
        label_btn_simpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btn_simpanLayout = new javax.swing.GroupLayout(btn_simpan);
        btn_simpan.setLayout(btn_simpanLayout);
        btn_simpanLayout.setHorizontalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_simpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_simpanLayout.setVerticalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        id_container.setText("id_container");

        fld_konfsandilama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        fld_konfsandilama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_konfsandilamaKeyReleased(evt);
            }
        });

        label_sandilama1.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_sandilama1.setText("Konfirmasi Sandi Lama");

        label_tidakcocok.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        label_tidakcocok.setForeground(new java.awt.Color(211, 47, 47));
        label_tidakcocok.setText("*Kata sandi tidak cocok");

        javax.swing.GroupLayout panel_bg_akunLayout = new javax.swing.GroupLayout(panel_bg_akun);
        panel_bg_akun.setLayout(panel_bg_akunLayout);
        panel_bg_akunLayout.setHorizontalGroup(
            panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_bg_akunLayout.createSequentialGroup()
                        .addComponent(label_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fld_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_bg_akunLayout.createSequentialGroup()
                            .addComponent(id_container)
                            .addGap(332, 332, 332)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                                .addComponent(label_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fld_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_bg_akunLayout.createSequentialGroup()
                                    .addComponent(label_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fld_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_bg_akunLayout.createSequentialGroup()
                                    .addComponent(label_sandilama1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_tidakcocok, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fld_konfsandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panel_bg_akunLayout.setVerticalGroup(
            panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sandilama1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_konfsandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(label_tidakcocok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_container, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void fld_konfsandilamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_konfsandilamaKeyReleased
        // TODO add your handling code here:
        String sandilama = fld_sandilama.getText();
        String konfsandilama = fld_konfsandilama.getText();

        if (!konfsandilama.equals(sandilama)) {
            label_tidakcocok.setVisible(true);
        } else {
            label_tidakcocok.setVisible(false);
        }
    }//GEN-LAST:event_fld_konfsandilamaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", true);

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_sandi_user dialog = new form_sandi_user(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }

    private void simpan() {

        String getid = id_container.getText();
        String username = fld_idpengguna.getText();
        String getpasslama = fld_sandilama.getText();
        String getpassabaru = fld_sandibaru.getText();

        if (empty(username) || empty(getpasslama) || empty(getpassabaru)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM login WHERE id_login = '" + getid + "' AND username = '" + username + "' AND password = '" + getpasslama + "'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);

                if (hasil.next()) {
                    try {
                        String sql = "UPDATE login SET username = ?, password = ? WHERE id_login = '" + getid + "'";
                        java.sql.PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                        stat.setString(1, username);
                        stat.setString(2, getpassabaru);
                        stat.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Sandi berhasil diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Gagal mengubah Sandi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Sandi lama salah!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Query Error!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_simpan;
    private javax.swing.JTextField fld_idpengguna;
    private javax.swing.JTextField fld_konfsandilama;
    private javax.swing.JTextField fld_sandibaru;
    private javax.swing.JTextField fld_sandilama;
    private javax.swing.JLabel id_container;
    private javax.swing.JLabel label_akun;
    private javax.swing.JLabel label_btn_simpan;
    private javax.swing.JLabel label_idpengguna;
    private javax.swing.JLabel label_sandibaru;
    private javax.swing.JLabel label_sandilama;
    private javax.swing.JLabel label_sandilama1;
    private javax.swing.JLabel label_tidakcocok;
    private javax.swing.JPanel panel_bg_akun;
    // End of variables declaration//GEN-END:variables
}
