/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import com.formdev.flatlaf.FlatLightLaf;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author alessandro
 */
public class form_tambah_datapegawai extends javax.swing.JDialog {

    /**
     * Creates new form form_tambah_datapegawai
     */
    private static Point point = new Point();

    public form_tambah_datapegawai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        setSize(1284, 687);
        setResizable(false);
        setLocationRelativeTo(null);

        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                setDefaultCloseOperation(form_tambah_datapegawai.DISPOSE_ON_CLOSE);
            }
        });

        initComponents();

        JTextFieldDateEditor d1 = (JTextFieldDateEditor) datechooser_tanggallahir.getDateEditor();
        d1.setEditable(false);

        JTextFieldDateEditor d2 = (JTextFieldDateEditor) datechooser_tanggalnaikpangkat.getDateEditor();
        d2.setEditable(false);

        JTextFieldDateEditor d3 = (JTextFieldDateEditor) datechooser_tanggalnaikjabatan.getDateEditor();
        d3.setEditable(false);

        tampil_cbbpangkat();
        tampil_cbbjabatan();
        tampil_cbbeselon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_tambah_datapegawai = new javax.swing.JPanel();
        label_tambah_datapegawai = new javax.swing.JLabel();
        label_nip = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_tempatlahir = new javax.swing.JLabel();
        label_tanggallahir = new javax.swing.JLabel();
        label_jabatan = new javax.swing.JLabel();
        label_pangkat = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        label_statuskawin = new javax.swing.JLabel();
        label_agama = new javax.swing.JLabel();
        label_jeniskelamin = new javax.swing.JLabel();
        fld_nip = new javax.swing.JTextField();
        fld_nama = new javax.swing.JTextField();
        fld_tempatlahir = new javax.swing.JTextField();
        datechooser_tanggallahir = new com.toedter.calendar.JDateChooser();
        cbb_jabatan = new javax.swing.JComboBox<>();
        cbb_jeniskelamin = new javax.swing.JComboBox<>();
        cbb_agama = new javax.swing.JComboBox<>();
        cbb_statuskawin = new javax.swing.JComboBox<>();
        cbb_pangkat = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JPanel();
        label_btn_simpan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fld_alamat = new javax.swing.JTextArea();
        label_eselon = new javax.swing.JLabel();
        cbb_eselon = new javax.swing.JComboBox<>();
        label_tgl_naikpangkat = new javax.swing.JLabel();
        datechooser_tanggalnaikpangkat = new com.toedter.calendar.JDateChooser();
        label_tgl_naikjabatan = new javax.swing.JLabel();
        datechooser_tanggalnaikjabatan = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bg_tambah_datapegawai.setBackground(new java.awt.Color(247, 247, 247));

        label_tambah_datapegawai.setFont(new java.awt.Font("Karla", 1, 36)); // NOI18N
        label_tambah_datapegawai.setForeground(new java.awt.Color(72, 60, 50));
        label_tambah_datapegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tambah_datapegawai.setText("TAMBAH DATA PEGAWAI");

        label_nip.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_nip.setText("NIP");

        label_nama.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_nama.setText("Nama");

        label_tempatlahir.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_tempatlahir.setText("Tempat Lahir");

        label_tanggallahir.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_tanggallahir.setText("Tanggal Lahir");

        label_jabatan.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_jabatan.setText("Jabatan");

        label_pangkat.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_pangkat.setText("Pangkat, Gol. / Ruang");

        label_alamat.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_alamat.setText("Alamat");

        label_statuskawin.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_statuskawin.setText("Status Kawin");

        label_agama.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_agama.setText("Agama");

        label_jeniskelamin.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_jeniskelamin.setText("Jenis Kelamin");

        fld_nip.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        fld_nip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fld_nipFocusLost(evt);
            }
        });
        fld_nip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fld_nipKeyTyped(evt);
            }
        });

        fld_nama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        fld_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fld_namaKeyTyped(evt);
            }
        });

        fld_tempatlahir.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        fld_tempatlahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fld_tempatlahirKeyTyped(evt);
            }
        });

        datechooser_tanggallahir.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        cbb_jabatan.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        cbb_jeniskelamin.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Laki-laki", "Perempuan" }));

        cbb_agama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Islam", "Kristen", "Katolik", "Buddha", "Hindu", "Khonghucu" }));

        cbb_statuskawin.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_statuskawin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Belum Kawin", "Kawin", "Cerai Hidup", "Cerai Mati" }));

        cbb_pangkat.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_pangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        btn_simpan.setBackground(new java.awt.Color(72, 60, 50));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });

        label_btn_simpan.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        label_btn_simpan.setForeground(new java.awt.Color(255, 255, 240));
        label_btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_32px.png"))); // NOI18N
        label_btn_simpan.setText("SIMPAN");
        label_btn_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIconTextGap(2);
        label_btn_simpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btn_simpanLayout = new javax.swing.GroupLayout(btn_simpan);
        btn_simpan.setLayout(btn_simpanLayout);
        btn_simpanLayout.setHorizontalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_simpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_simpanLayout.setVerticalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        fld_alamat.setColumns(20);
        fld_alamat.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        fld_alamat.setLineWrap(true);
        fld_alamat.setWrapStyleWord(true);
        fld_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fld_alamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(fld_alamat);

        label_eselon.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_eselon.setText("Eselon");

        cbb_eselon.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        cbb_eselon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        label_tgl_naikpangkat.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_tgl_naikpangkat.setText("Tanggal Kenaikan Pangkat");

        datechooser_tanggalnaikpangkat.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        label_tgl_naikjabatan.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_tgl_naikjabatan.setText("Tanggal Kenaikan Jabatan");

        datechooser_tanggalnaikjabatan.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        javax.swing.GroupLayout panel_bg_tambah_datapegawaiLayout = new javax.swing.GroupLayout(panel_bg_tambah_datapegawai);
        panel_bg_tambah_datapegawai.setLayout(panel_bg_tambah_datapegawaiLayout);
        panel_bg_tambah_datapegawaiLayout.setHorizontalGroup(
            panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tambah_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_eselon, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbb_eselon, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_tgl_naikjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datechooser_tanggalnaikjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(626, 626, 626))
                    .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_nip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_tempatlahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_tanggallahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fld_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_tempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datechooser_tanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbb_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addComponent(label_tgl_naikpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datechooser_tanggalnaikpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_agama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_statuskawin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbb_agama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_jeniskelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_statuskawin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panel_bg_tambah_datapegawaiLayout.setVerticalGroup(
            panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tambah_datapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datechooser_tanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_tempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fld_tempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(label_tanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_tgl_naikpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datechooser_tanggalnaikpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_bg_tambah_datapegawaiLayout.createSequentialGroup()
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_statuskawin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_statuskawin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tgl_naikjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datechooser_tanggalnaikjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bg_tambah_datapegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_eselon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_eselon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_tambah_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_tambah_datapegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void fld_nipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_nipKeyTyped
        // TODO add your handling code here:
        if ((fld_nip.getText() + evt.getKeyChar()).length() > 18) {
            evt.consume();
        }
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_fld_nipKeyTyped

    private void fld_nipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fld_nipFocusLost
        // TODO add your handling code here:
        String tahun = fld_nip.getText().substring(0, 4);
        String bulan = fld_nip.getText().substring(4, 6);
        String tanggal = fld_nip.getText().substring(6, 8);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd", Locale.ENGLISH);

        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");

        try {
            Date date = format.parse(fld_nip.getText().substring(0, 8));
            datechooser_tanggallahir.setDate(date);
        } catch (ParseException ex) {

        }

        String jenis_kelamin = fld_nip.getText().substring(14, 15);
        if (jenis_kelamin.equals("1")) {
            cbb_jeniskelamin.setSelectedIndex(1);
        } else if (jenis_kelamin.equals("2")) {
            cbb_jeniskelamin.setSelectedIndex(2);
        } else {

        }
    }//GEN-LAST:event_fld_nipFocusLost

    private void fld_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_namaKeyTyped
        // TODO add your handling code here:
        if ((fld_nama.getText() + evt.getKeyChar()).length() > 255) {
            evt.consume();
        }
        char vChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_fld_namaKeyTyped

    private void fld_tempatlahirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_tempatlahirKeyTyped
        // TODO add your handling code here:
        if ((fld_tempatlahir.getText() + evt.getKeyChar()).length() > 255) {
            evt.consume();
        }
        char vChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(vChar)
                || (Character.isDigit(vChar))
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_fld_tempatlahirKeyTyped

    private void fld_alamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_alamatKeyTyped
        // TODO add your handling code here:
        if ((fld_alamat.getText() + evt.getKeyChar()).length() > 255) {
            evt.consume();
        }
    }//GEN-LAST:event_fld_alamatKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", true);

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_tambah_datapegawai dialog = new form_tambah_datapegawai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void tampil_cbbpangkat() {
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM pangkat ORDER BY id_pangkat ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                cbb_pangkat.addItem(hasil.getString("nama_pangkat"));
            }

            hasil.close();
            stat.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Daftar Pangkat!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void tampil_cbbjabatan() {
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM jabatan ORDER BY id_jabatan ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                cbb_jabatan.addItem(hasil.getString("nama_jabatan"));
            }

            hasil.close();
            stat.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Daftar Jabatan!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void tampil_cbbeselon() {
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM eselon ORDER BY id_eselon ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                cbb_eselon.addItem(hasil.getString("nama_eselon"));
            }

            hasil.close();
            stat.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Daftar Eselon!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }

    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }

    private void simpan() {

        String getpangkat = cbb_pangkat.getSelectedItem().toString();
        int getindexpangkat = cbb_pangkat.getSelectedIndex();
        String getjabatan = cbb_jabatan.getSelectedItem().toString();
        int getindexjabatan = cbb_jabatan.getSelectedIndex();
        String geteselon = cbb_eselon.getSelectedItem().toString();
        int getindexeselon = cbb_eselon.getSelectedIndex();
        String getnip = fld_nip.getText();
        String getnama = fld_nama.getText();
        String gettempatlahir = fld_tempatlahir.getText();
        String getjeniskelamin = cbb_jeniskelamin.getSelectedItem().toString();
        int getindexjeniskelamin = cbb_jeniskelamin.getSelectedIndex();
        String getagama = cbb_agama.getSelectedItem().toString();
        int getindexagama = cbb_agama.getSelectedIndex();
        String getstatuskawin = cbb_statuskawin.getSelectedItem().toString();
        int getindexstatuskawin = cbb_statuskawin.getSelectedIndex();
        String getalamat = fld_alamat.getText();

        if (empty(getnip) || empty(getnama) || empty(gettempatlahir) || datechooser_tanggallahir.getDate() == null || getindexpangkat == 0 || getindexjabatan == 0 || getindexeselon == 0 || getindexjeniskelamin == 0 || getindexagama == 0 || getindexstatuskawin == 0 || empty(getalamat) || datechooser_tanggalnaikpangkat.getDate() == null || datechooser_tanggalnaikjabatan.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String gettanggallahir = sdf.format(datechooser_tanggallahir.getDate());
            String gettanggalnaik_p = sdf.format(datechooser_tanggalnaikpangkat.getDate());
            String gettanggalnaik_j = sdf.format(datechooser_tanggalnaikjabatan.getDate());

            Date dob = datechooser_tanggallahir.getDate();
            Date pangkat = datechooser_tanggalnaikpangkat.getDate();
            Date jabatan = datechooser_tanggalnaikjabatan.getDate();

            LocalDate today = LocalDate.now();
            LocalDate birthday = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate localpangkat = pangkat.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate localjabatan = jabatan.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            Period period_bd = Period.between(birthday, today);
            Period period_p = Period.between(birthday, localpangkat);
            Period period_j = Period.between(birthday, localjabatan);

            if (period_bd.getYears() < 18) {
                JOptionPane.showMessageDialog(null, "Usia minimal 18 tahun.", "Peringatan!", JOptionPane.WARNING_MESSAGE);
            } else if (period_p.getYears() < 18 || period_j.getYears() < 18 || pangkat.before(dob) || jabatan.before(dob)) {
                JOptionPane.showMessageDialog(null, "Tanggal kenaikan pangkat atau jabatan tidak valid.", "Peringatan!", JOptionPane.WARNING_MESSAGE);
            } else if (jabatan.before(pangkat)) {
                JOptionPane.showMessageDialog(null, "Tanggal kenaikan jabatan kurang dari tanggal kenaikan pangkat..", "Peringatan!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    Connection con = new database.connection().configDB();
                    String get = "SELECT * FROM datapegawai WHERE nip = '" + getnip + "'";
                    java.sql.Statement st = con.createStatement();
                    java.sql.ResultSet hasil = st.executeQuery(get);

                    if (hasil.next()) {
                        JOptionPane.showMessageDialog(null, "Data dengan NIP yang sama sudah terdaftar!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        try {
                            String sql = "INSERT INTO datapegawai VALUES (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                            java.sql.PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                            stat.setInt(1, getindexpangkat);
                            stat.setInt(2, getindexjabatan);
                            stat.setInt(3, getindexeselon);
                            stat.setString(4, getnip);
                            stat.setString(5, getnama);
                            stat.setString(6, gettempatlahir);
                            stat.setString(7, gettanggallahir);
                            stat.setInt(8, getindexjeniskelamin);
                            stat.setString(9, getjeniskelamin);
                            stat.setInt(10, getindexagama);
                            stat.setString(11, getagama);
                            stat.setInt(12, getindexstatuskawin);
                            stat.setString(13, getstatuskawin);
                            stat.setString(14, getalamat);
                            stat.setString(15, gettanggalnaik_p);
                            stat.setString(16, gettanggalnaik_j);
                            stat.executeUpdate();
                            stat.close();

                            String sql_next = "INSERT INTO login VALUES (null, ?, ?, ?)";
                            java.sql.PreparedStatement stat_next = (PreparedStatement) con.prepareStatement(sql_next);
                            stat_next.setString(1, getnip);
                            stat_next.setString(2, getnip);
                            stat_next.setString(3, "user");
                            stat_next.executeUpdate();
                            stat_next.close();

                            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan\n\n"
                                    + "Akun pengguna telah dibuat secara otomatis.\n"
                                    + "ID Pengguna: " + getnip + "\n"
                                    + "Kata Sandi: " + getnip + "", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                            this.setVisible(false);

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Gagal menambah data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                        } finally {
                            hasil.close();
                            st.close();
                            con.close();
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Query Error!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_simpan;
    private javax.swing.JComboBox<String> cbb_agama;
    private javax.swing.JComboBox<String> cbb_eselon;
    private javax.swing.JComboBox<String> cbb_jabatan;
    private javax.swing.JComboBox<String> cbb_jeniskelamin;
    private javax.swing.JComboBox<String> cbb_pangkat;
    private javax.swing.JComboBox<String> cbb_statuskawin;
    private com.toedter.calendar.JDateChooser datechooser_tanggallahir;
    private com.toedter.calendar.JDateChooser datechooser_tanggalnaikjabatan;
    private com.toedter.calendar.JDateChooser datechooser_tanggalnaikpangkat;
    private javax.swing.JTextArea fld_alamat;
    private javax.swing.JTextField fld_nama;
    private javax.swing.JTextField fld_nip;
    private javax.swing.JTextField fld_tempatlahir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_agama;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_btn_simpan;
    private javax.swing.JLabel label_eselon;
    private javax.swing.JLabel label_jabatan;
    private javax.swing.JLabel label_jeniskelamin;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nip;
    private javax.swing.JLabel label_pangkat;
    private javax.swing.JLabel label_statuskawin;
    private javax.swing.JLabel label_tambah_datapegawai;
    private javax.swing.JLabel label_tanggallahir;
    private javax.swing.JLabel label_tempatlahir;
    private javax.swing.JLabel label_tgl_naikjabatan;
    private javax.swing.JLabel label_tgl_naikpangkat;
    private javax.swing.JPanel panel_bg_tambah_datapegawai;
    // End of variables declaration//GEN-END:variables
}
