/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author alessandro
 */
public class form_akun extends javax.swing.JDialog {

    /**
     * Creates new form form_akun
     */
    DefaultTableModel tabel1 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private static Point point = new Point();

    public form_akun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        setSize(800, 600);
        setResizable(false);
        setLocationRelativeTo(null);

        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        initComponents();

        tampilakun();
        id_container.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_akun = new javax.swing.JPanel();
        label_akun = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_akun = new javax.swing.JTable();
        label_idpengguna = new javax.swing.JLabel();
        label_sandilama = new javax.swing.JLabel();
        label_sandibaru = new javax.swing.JLabel();
        fld_idpengguna = new javax.swing.JTextField();
        fld_sandilama = new javax.swing.JTextField();
        fld_sandibaru = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JPanel();
        label_btn_simpan = new javax.swing.JLabel();
        id_container = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bg_akun.setBackground(new java.awt.Color(247, 247, 247));

        label_akun.setFont(new java.awt.Font("Karla", 1, 36)); // NOI18N
        label_akun.setForeground(new java.awt.Color(72, 60, 50));
        label_akun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_akun.setText("PENGATURAN AKUN");

        tbl_akun.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N
        tbl_akun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_akunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_akun);

        label_idpengguna.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_idpengguna.setText("ID Pengguna");

        label_sandilama.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_sandilama.setText("Sandi Lama");

        label_sandibaru.setFont(new java.awt.Font("Karla", 1, 18)); // NOI18N
        label_sandibaru.setText("Sandi Baru");

        fld_idpengguna.setEditable(false);
        fld_idpengguna.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        fld_sandilama.setEditable(false);
        fld_sandilama.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        fld_sandibaru.setFont(new java.awt.Font("Karla", 0, 18)); // NOI18N

        btn_simpan.setBackground(new java.awt.Color(72, 60, 50));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });

        label_btn_simpan.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        label_btn_simpan.setForeground(new java.awt.Color(255, 255, 240));
        label_btn_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_32px.png"))); // NOI18N
        label_btn_simpan.setText("SIMPAN");
        label_btn_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_btn_simpan.setIconTextGap(2);
        label_btn_simpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btn_simpanLayout = new javax.swing.GroupLayout(btn_simpan);
        btn_simpan.setLayout(btn_simpanLayout);
        btn_simpanLayout.setHorizontalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_simpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_simpanLayout.setVerticalGroup(
            btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        id_container.setText("id_container");

        javax.swing.GroupLayout panel_bg_akunLayout = new javax.swing.GroupLayout(panel_bg_akun);
        panel_bg_akun.setLayout(panel_bg_akunLayout);
        panel_bg_akunLayout.setHorizontalGroup(
            panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_bg_akunLayout.createSequentialGroup()
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                                .addComponent(label_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fld_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_bg_akunLayout.createSequentialGroup()
                                    .addComponent(label_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fld_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bg_akunLayout.createSequentialGroup()
                                    .addComponent(label_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fld_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_container)))
                    .addComponent(jScrollPane1))
                .addGap(32, 32, 32))
        );
        panel_bg_akunLayout.setVerticalGroup(
            panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bg_akunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_bg_akunLayout.createSequentialGroup()
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_sandilama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_bg_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_sandibaru, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_bg_akunLayout.createSequentialGroup()
                        .addComponent(id_container)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
        simpan();
        tampilakun();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void tbl_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_akunMouseClicked
        // TODO add your handling code here:
        int baris = tbl_akun.getSelectedRow();

        id_container.setText(tabel1.getValueAt(baris, 0).toString());
        fld_idpengguna.setText(tabel1.getValueAt(baris, 2).toString());
        fld_sandilama.setText(tabel1.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbl_akunMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", true);

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_akun dialog = new form_akun(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void header() {
        JTableHeader tab = tbl_akun.getTableHeader();
        tab.setFont(new Font("Karla", Font.BOLD, 18));
        tab.setPreferredSize(new Dimension(128, 32));
        /*TableCellRenderer rendererFromHeader = tbl_datapegawai.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);*/

        tbl_akun.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_akun.getColumnModel().getColumn(0).setMaxWidth(0);

        TableColumn c1 = tbl_akun.getColumnModel().getColumn(1);
        c1.setMaxWidth(64);
        c1.setMinWidth(64);

    }

    private void tampilakun() {
        Object[] baris = {"ID", "No.", "ID Pengguna", "Kata Sandi"};
        tabel1 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tbl_akun.setModel(tabel1);
        header();

        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT *, @rownum := @rownum + 1 AS number FROM login t, (SELECT @rownum := 0) r";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                String id_login = hasil.getString("id_login");
                String no = Integer.toString(hasil.getInt("number"));
                String username = hasil.getString("username");
                String password = hasil.getString("password");

                String[] data = {id_login, no, username, password};
                tabel1.addRow(data);
                tbl_akun.setRowHeight(30);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Data Akun!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }

    private void simpan() {

        String getid = id_container.getText();
        String getuser = fld_idpengguna.getText();
        String getpasslama = fld_sandilama.getText();
        String getpassabaru = fld_sandibaru.getText();

        if (empty(getuser) || empty(getpasslama) || empty(getpassabaru)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM login WHERE id_login = '" + getid + "' AND username = '" + getuser + "' AND password = '" + getpasslama + "'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);

                if (hasil.next()) {
                    try {
                        String sql = "UPDATE login SET username = ?, password = ? WHERE id_login = '" + getid + "'";
                        java.sql.PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                        stat.setString(1, getuser);
                        stat.setString(2, getpassabaru);
                        stat.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Sandi berhasil diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        clearfield();

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Gagal mengubah sandi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Anda belum memilih akun!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }

        }
    }

    private void clearfield() {
        id_container.setText("");
        fld_idpengguna.setText("");
        fld_sandilama.setText("");
        fld_sandibaru.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_simpan;
    private javax.swing.JTextField fld_idpengguna;
    private javax.swing.JTextField fld_sandibaru;
    private javax.swing.JTextField fld_sandilama;
    private javax.swing.JLabel id_container;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_akun;
    private javax.swing.JLabel label_btn_simpan;
    private javax.swing.JLabel label_idpengguna;
    private javax.swing.JLabel label_sandibaru;
    private javax.swing.JLabel label_sandilama;
    private javax.swing.JPanel panel_bg_akun;
    private javax.swing.JTable tbl_akun;
    // End of variables declaration//GEN-END:variables
}
